"""
Activity for computing similarity between embeddings.

This activity demonstrates computing cosine similarity between vector embeddings,
typically used after embeddings are generated by the generate_embeddings activity.
"""
import logging
from ..config import workflow_runtime

logger = logging.getLogger(__name__)


@workflow_runtime.activity(name='compute_similarity')
def compute_similarity(_ctx, input_data: dict) -> dict:
    """
    Compute cosine similarity between two sets of embeddings.

    Args:
        _ctx: Activity context
        input_data: Dictionary with 'embeddings1' and 'embeddings2' (lists of floats)

    Returns:
        Dictionary with similarity score
    """
    try:
        import numpy as np

        emb1 = np.array(input_data.get("embeddings1", []))
        emb2 = np.array(input_data.get("embeddings2", []))

        if emb1.size == 0 or emb2.size == 0:
            return {"similarity": 0.0, "error": "Empty embeddings provided"}

        # Compute cosine similarity
        similarity = float(np.dot(emb1, emb2) / (np.linalg.norm(emb1) * np.linalg.norm(emb2)))

        logger.info(f"Computed similarity: {similarity:.4f}")

        return {
            "similarity": similarity,
            "interpretation": _interpret_similarity(similarity)
        }

    except Exception as e:
        logger.error(f"Error computing similarity: {e}")
        return {"similarity": 0.0, "error": str(e)}


def _interpret_similarity(score: float) -> str:
    """Provide human-readable interpretation of similarity score."""
    if score >= 0.9:
        return "very_similar"
    elif score >= 0.7:
        return "similar"
    elif score >= 0.5:
        return "somewhat_similar"
    elif score >= 0.3:
        return "slightly_similar"
    else:
        return "dissimilar"
